
# Site settings
title: Emily's Blog
description: design, technology, and society
baseurl: "/blog" # folder where your site lives, e.g. /web1-sp - needs to start with a slash
url: "http://emchun.github.io" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
